### ISSUE TITLE
Default value for num_examples_per_instance

### ISSUE THREAD

**Issue by jeff-hernandez** [FeatureLabs/compose#47]
A user can use a large number to get all possibles examples. Would it be better to get all possibles examples by default when `num_examples_per_instance` is `None` , `-1`  or `inf`?

**Comment by kmax12** [comment]
I think a user should be able to provide `-i` or `inf` to get all possible examples. 

for now, let's not set a default value. the user must provide a `num_examples_per_instance`. this will require them to understand that this parameter exists rather than us magically selecting some value. in the future, we can always create a default value, if we change our minds
